//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiMedicalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int IdAppointment { get; set; }
        public System.DateTime Date { get; set; }
        public int IdDoctor { get; set; }
        public Nullable<int> IdPatient { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Status Status { get; set; }
    }
}
